/**
 * Mock BuildingConnected Data
 * 10 realistic mock projects matching BuildingConnected API structure
 */

import { BuildingConnectedProject } from '@/types/buildingconnected';
import { BidPackage } from '@/types/bidPackage';
import { generateId } from './generateId';

// Helper to generate BuildingConnected-style IDs (24 characters)
const generateBCId = () => generateId().substring(0, 24).padEnd(24, '0');

// Helper to create dates
const daysFromNow = (days: number) => {
  const date = new Date();
  date.setDate(date.getDate() + days);
  return date;
};

// Generate project IDs (diagrams will be uploaded by users, not in mock data)
const project1BcId = generateBCId();
const project2BcId = generateBCId();
const project3BcId = generateBCId();
const project4BcId = generateBCId();
const project5BcId = generateBCId();
const project6BcId = generateBCId();
const project7BcId = generateBCId();
const project8BcId = generateBCId();
const project9BcId = generateBCId();
const project10BcId = generateBCId();

export const mockBuildingConnectedProjects: BuildingConnectedProject[] = [
  {
    id: generateId(),
    bcProjectId: project1BcId,
    name: 'Downtown Medical Center Expansion',
    projectNumber: 'DMC-2025-001',
    description: 'Three-story medical office building addition with state-of-the-art diagnostic imaging center and outpatient surgery suites.',
    status: 'bidding',
    bidDueDate: daysFromNow(14),
    expectedStartDate: daysFromNow(45),
    expectedEndDate: daysFromNow(425),
    location: {
      address: '1250 Medical Plaza Drive',
      city: 'San Francisco',
      state: 'CA',
      zipCode: '94102',
      country: 'USA',
    },
    projectSize: 125000,
    projectSizeUnit: 'SF',
    projectValue: 45000000,
    marketSector: 'Healthcare',
    typeOfWork: 'New Construction',
    architect: 'Perkins+Will Architecture',
    client: 'Bay Area Health Systems',
    accountManager: 'Sarah Chen',
    owningOffice: 'San Francisco',
    feePercentage: 6.5,
    lastSyncedAt: new Date(),
    syncStatus: 'synced',
    diagrams: [],
    createdAt: daysFromNow(-30),
    updatedAt: daysFromNow(-1),
  },
  {
    id: generateId(),
    bcProjectId: project2BcId,
    name: 'Riverside High School Modernization',
    projectNumber: 'RHS-2025-012',
    description: 'Complete renovation of 1960s-era high school including new STEM labs, library media center, and performing arts wing.',
    status: 'active',
    bidDueDate: daysFromNow(21),
    expectedStartDate: daysFromNow(60),
    expectedEndDate: daysFromNow(545),
    location: {
      address: '4500 River Road',
      city: 'Portland',
      state: 'OR',
      zipCode: '97214',
      country: 'USA',
    },
    projectSize: 180000,
    projectSizeUnit: 'SF',
    projectValue: 62000000,
    marketSector: 'Education',
    typeOfWork: 'Renovation',
    architect: 'BORA Architecture',
    client: 'Portland Public Schools',
    accountManager: 'Michael Rodriguez',
    owningOffice: 'Portland',
    feePercentage: 5.8,
    lastSyncedAt: new Date(),
    syncStatus: 'synced',
    diagrams: [],
    createdAt: daysFromNow(-45),
    updatedAt: daysFromNow(-2),
  },
  {
    id: generateId(),
    bcProjectId: project3BcId,
    name: 'Tech Campus Building 7',
    projectNumber: 'TC7-2025-003',
    description: 'Five-story office building with collaborative workspaces, rooftop amenities, and underground parking for 300 vehicles.',
    status: 'bidding',
    bidDueDate: daysFromNow(7),
    expectedStartDate: daysFromNow(30),
    expectedEndDate: daysFromNow(395),
    location: {
      address: '1 Innovation Way',
      city: 'Austin',
      state: 'TX',
      zipCode: '78701',
      country: 'USA',
    },
    projectSize: 210000,
    projectSizeUnit: 'SF',
    projectValue: 78000000,
    marketSector: 'Commercial',
    typeOfWork: 'New Construction',
    architect: 'Gensler',
    client: 'TechCorp Properties LLC',
    accountManager: 'Jennifer Park',
    owningOffice: 'Austin',
    feePercentage: 7.2,
    lastSyncedAt: new Date(),
    syncStatus: 'synced',
    diagrams: [],
    createdAt: daysFromNow(-20),
    updatedAt: new Date(),
  },
  {
    id: generateId(),
    bcProjectId: project4BcId,
    name: 'Metro Station Transit Hub',
    projectNumber: 'MST-2025-089',
    description: 'Multi-modal transit center with bus rapid transit platforms, bike facilities, retail spaces, and 500-unit residential tower.',
    status: 'active',
    bidDueDate: daysFromNow(28),
    expectedStartDate: daysFromNow(90),
    expectedEndDate: daysFromNow(820),
    location: {
      address: '800 Transit Avenue',
      city: 'Seattle',
      state: 'WA',
      zipCode: '98101',
      country: 'USA',
    },
    projectSize: 450000,
    projectSizeUnit: 'SF',
    projectValue: 185000000,
    marketSector: 'Infrastructure',
    typeOfWork: 'New Construction',
    architect: 'SOM (Skidmore, Owings & Merrill)',
    client: 'Seattle Transit Authority',
    accountManager: 'David Kim',
    owningOffice: 'Seattle',
    feePercentage: 4.5,
    lastSyncedAt: new Date(),
    syncStatus: 'synced',
    diagrams: [],
    createdAt: daysFromNow(-60),
    updatedAt: daysFromNow(-3),
  },
  {
    id: generateId(),
    bcProjectId: project5BcId,
    name: 'Lakeside Luxury Apartments',
    projectNumber: 'LLA-2025-045',
    description: 'Eight-story mixed-use development with 150 luxury apartments, ground-floor retail, and two levels of parking.',
    status: 'bidding',
    bidDueDate: daysFromNow(10),
    expectedStartDate: daysFromNow(40),
    expectedEndDate: daysFromNow(490),
    location: {
      address: '2200 Lakeshore Boulevard',
      city: 'Chicago',
      state: 'IL',
      zipCode: '60601',
      country: 'USA',
    },
    projectSize: 185000,
    projectSizeUnit: 'SF',
    projectValue: 52000000,
    marketSector: 'Residential',
    typeOfWork: 'New Construction',
    architect: 'Studio Gang',
    client: 'Lakeside Development Partners',
    accountManager: 'Amanda Torres',
    owningOffice: 'Chicago',
    feePercentage: 6.0,
    lastSyncedAt: new Date(),
    syncStatus: 'synced',
    diagrams: [],
    createdAt: daysFromNow(-25),
    updatedAt: daysFromNow(-1),
  },
  {
    id: generateId(),
    bcProjectId: project6BcId,
    name: 'Regional Data Center Phase 2',
    projectNumber: 'RDC-2025-P2',
    description: 'Mission-critical Tier III data center with 20MW power capacity, advanced cooling systems, and redundant infrastructure.',
    status: 'active',
    bidDueDate: daysFromNow(35),
    expectedStartDate: daysFromNow(75),
    expectedEndDate: daysFromNow(440),
    location: {
      address: '15000 Data Center Parkway',
      city: 'Phoenix',
      state: 'AZ',
      zipCode: '85001',
      country: 'USA',
    },
    projectSize: 95000,
    projectSizeUnit: 'SF',
    projectValue: 125000000,
    marketSector: 'Industrial',
    typeOfWork: 'New Construction',
    architect: 'HDR Architecture',
    client: 'CloudScale Infrastructure',
    accountManager: 'Robert Martinez',
    owningOffice: 'Phoenix',
    feePercentage: 5.5,
    lastSyncedAt: new Date(),
    syncStatus: 'synced',
    diagrams: [],
    createdAt: daysFromNow(-40),
    updatedAt: daysFromNow(-5),
  },
  {
    id: generateId(),
    bcProjectId: project7BcId,
    name: 'Historic Theater Restoration',
    projectNumber: 'HTR-2025-007',
    description: 'Complete restoration of 1920s movie palace including seismic upgrades, modern AV systems, and accessibility improvements.',
    status: 'bidding',
    bidDueDate: daysFromNow(18),
    expectedStartDate: daysFromNow(50),
    expectedEndDate: daysFromNow(415),
    location: {
      address: '750 Broadway',
      city: 'New York',
      state: 'NY',
      zipCode: '10003',
      country: 'USA',
    },
    projectSize: 42000,
    projectSizeUnit: 'SF',
    projectValue: 28000000,
    marketSector: 'Cultural',
    typeOfWork: 'Renovation',
    architect: 'Beyer Blinder Belle',
    client: 'Historic Preservation Trust',
    accountManager: 'Elizabeth White',
    owningOffice: 'New York',
    feePercentage: 7.5,
    lastSyncedAt: new Date(),
    syncStatus: 'synced',
    diagrams: [],
    createdAt: daysFromNow(-35),
    updatedAt: daysFromNow(-2),
  },
  {
    id: generateId(),
    bcProjectId: project8BcId,
    name: 'University Science Complex',
    projectNumber: 'USC-2025-023',
    description: 'Two connected buildings housing chemistry, biology, and physics labs with vivarium, greenhouse, and collaborative research spaces.',
    status: 'active',
    bidDueDate: daysFromNow(42),
    expectedStartDate: daysFromNow(90),
    expectedEndDate: daysFromNow(635),
    location: {
      address: '100 Campus Drive',
      city: 'Boston',
      state: 'MA',
      zipCode: '02115',
      country: 'USA',
    },
    projectSize: 240000,
    projectSizeUnit: 'SF',
    projectValue: 95000000,
    marketSector: 'Education',
    typeOfWork: 'New Construction',
    architect: 'Payette Associates',
    client: 'Northeastern University',
    accountManager: 'Thomas Anderson',
    owningOffice: 'Boston',
    feePercentage: 6.8,
    lastSyncedAt: new Date(),
    syncStatus: 'synced',
    diagrams: [],
    createdAt: daysFromNow(-50),
    updatedAt: daysFromNow(-4),
  },
  {
    id: generateId(),
    bcProjectId: project9BcId,
    name: 'Airport Terminal C Expansion',
    projectNumber: 'ATC-2025-101',
    description: 'New international terminal with 12 gates, customs facility, retail concourse, and automated people mover connection.',
    status: 'awarded',
    bidDueDate: daysFromNow(-15), // Past due - already awarded
    expectedStartDate: daysFromNow(15),
    expectedEndDate: daysFromNow(915),
    location: {
      address: '1 Airport Boulevard',
      city: 'Denver',
      state: 'CO',
      zipCode: '80249',
      country: 'USA',
    },
    projectSize: 520000,
    projectSizeUnit: 'SF',
    projectValue: 310000000,
    marketSector: 'Infrastructure',
    typeOfWork: 'New Construction',
    architect: 'Fentress Architects',
    client: 'Denver Airport Authority',
    accountManager: 'Jessica Martinez',
    owningOffice: 'Denver',
    feePercentage: 4.2,
    lastSyncedAt: new Date(),
    syncStatus: 'synced',
    diagrams: [],
    createdAt: daysFromNow(-90),
    updatedAt: daysFromNow(-10),
  },
  {
    id: generateId(),
    bcProjectId: project10BcId,
    name: 'Waterfront Hotel & Conference Center',
    projectNumber: 'WHC-2025-056',
    description: '12-story hotel with 350 rooms, 50,000 SF conference center, rooftop restaurant, spa, and marina-side amenities.',
    status: 'bidding',
    bidDueDate: daysFromNow(25),
    expectedStartDate: daysFromNow(65),
    expectedEndDate: daysFromNow(580),
    location: {
      address: '300 Harborfront Drive',
      city: 'Miami',
      state: 'FL',
      zipCode: '33131',
      country: 'USA',
    },
    projectSize: 385000,
    projectSizeUnit: 'SF',
    projectValue: 142000000,
    marketSector: 'Hospitality',
    typeOfWork: 'New Construction',
    architect: 'Arquitectonica',
    client: 'Coastal Hospitality Group',
    accountManager: 'Carlos Hernandez',
    owningOffice: 'Miami',
    feePercentage: 5.2,
    lastSyncedAt: new Date(),
    syncStatus: 'synced',
    diagrams: [],
    createdAt: daysFromNow(-28),
    updatedAt: daysFromNow(-1),
  },
];

// Mock bid packages for each project (2-4 packages per project)
export const mockBidPackages: BidPackage[] = [
  // Project 1: Downtown Medical Center Expansion
  {
    id: generateId(),
    bcBidPackageId: generateBCId(),
    bcProjectId: mockBuildingConnectedProjects[0].bcProjectId,
    name: 'Site Work & Foundations',
    description: 'Site preparation, excavation, shoring, and foundation work',
    scope: 'Includes demolition, grading, utility relocation, caisson installation, and grade beams',
    bidDueDate: daysFromNow(14),
    status: 'bidding',
    progress: 0,
    createdAt: daysFromNow(-30),
    updatedAt: daysFromNow(-1),
  },
  {
    id: generateId(),
    bcBidPackageId: generateBCId(),
    bcProjectId: mockBuildingConnectedProjects[0].bcProjectId,
    name: 'Medical Gas & Plumbing',
    description: 'Medical gas systems, plumbing, and fire protection',
    scope: 'Complete medical gas piping, zone valves, alarm systems, domestic water, waste, and sprinkler systems',
    bidDueDate: daysFromNow(14),
    status: 'bidding',
    progress: 0,
    createdAt: daysFromNow(-30),
    updatedAt: daysFromNow(-1),
  },
  {
    id: generateId(),
    bcBidPackageId: generateBCId(),
    bcProjectId: mockBuildingConnectedProjects[0].bcProjectId,
    name: 'Structural Steel & Envelope',
    description: 'Structural steel and building envelope systems',
    scope: 'Steel erection, metal studs, curtain wall, roofing, and waterproofing',
    bidDueDate: daysFromNow(14),
    status: 'active',
    progress: 15,
    createdAt: daysFromNow(-30),
    updatedAt: daysFromNow(-1),
  },

  // Project 2: Riverside High School
  {
    id: generateId(),
    bcBidPackageId: generateBCId(),
    bcProjectId: mockBuildingConnectedProjects[1].bcProjectId,
    name: 'Selective Demolition',
    description: 'Interior demolition and hazardous material abatement',
    scope: 'Asbestos abatement, lead paint removal, selective demo of existing partitions and systems',
    bidDueDate: daysFromNow(21),
    status: 'active',
    progress: 0,
    createdAt: daysFromNow(-45),
    updatedAt: daysFromNow(-2),
  },
  {
    id: generateId(),
    bcBidPackageId: generateBCId(),
    bcProjectId: mockBuildingConnectedProjects[1].bcProjectId,
    name: 'MEP Systems',
    description: 'Complete mechanical, electrical, and plumbing renovation',
    scope: 'HVAC replacement, electrical service upgrade, new plumbing systems, fire alarm, and data infrastructure',
    bidDueDate: daysFromNow(21),
    status: 'active',
    progress: 10,
    createdAt: daysFromNow(-45),
    updatedAt: daysFromNow(-2),
  },

  // Project 3: Tech Campus Building 7
  {
    id: generateId(),
    bcBidPackageId: generateBCId(),
    bcProjectId: mockBuildingConnectedProjects[2].bcProjectId,
    name: 'Core & Shell',
    description: 'Complete building core and shell construction',
    scope: 'Foundations, structural frame, exterior envelope, roofing, and parking structure',
    bidDueDate: daysFromNow(7),
    status: 'bidding',
    progress: 0,
    createdAt: daysFromNow(-20),
    updatedAt: new Date(),
  },
  {
    id: generateId(),
    bcBidPackageId: generateBCId(),
    bcProjectId: mockBuildingConnectedProjects[2].bcProjectId,
    name: 'Tenant Improvements',
    description: 'Interior fit-out and finishes',
    scope: 'Interior partitions, ceilings, flooring, millwork, doors, and specialties',
    bidDueDate: daysFromNow(7),
    status: 'draft',
    progress: 0,
    createdAt: daysFromNow(-20),
    updatedAt: new Date(),
  },
  {
    id: generateId(),
    bcBidPackageId: generateBCId(),
    bcProjectId: mockBuildingConnectedProjects[2].bcProjectId,
    name: 'Technology Infrastructure',
    description: 'Data, AV, security, and building automation',
    scope: 'Structured cabling, access control, CCTV, AV systems, and building management systems',
    bidDueDate: daysFromNow(7),
    status: 'draft',
    progress: 0,
    createdAt: daysFromNow(-20),
    updatedAt: new Date(),
  },

  // Project 4: Metro Station Transit Hub
  {
    id: generateId(),
    bcBidPackageId: generateBCId(),
    bcProjectId: mockBuildingConnectedProjects[3].bcProjectId,
    name: 'Civil & Utilities',
    description: 'Site civil work and utility infrastructure',
    scope: 'Grading, storm drainage, water, sewer, gas, electric, telecom utilities',
    bidDueDate: daysFromNow(28),
    status: 'active',
    progress: 5,
    createdAt: daysFromNow(-60),
    updatedAt: daysFromNow(-3),
  },
  {
    id: generateId(),
    bcBidPackageId: generateBCId(),
    bcProjectId: mockBuildingConnectedProjects[3].bcProjectId,
    name: 'Transit Platform Systems',
    description: 'Bus platforms, canopies, and passenger amenities',
    scope: 'Platform construction, weather protection, seating, signage, and wayfinding',
    bidDueDate: daysFromNow(28),
    status: 'active',
    progress: 0,
    createdAt: daysFromNow(-60),
    updatedAt: daysFromNow(-3),
  },
  {
    id: generateId(),
    bcBidPackageId: generateBCId(),
    bcProjectId: mockBuildingConnectedProjects[3].bcProjectId,
    name: 'Residential Tower',
    description: '500-unit residential tower construction',
    scope: 'Complete residential tower including structure, envelope, MEP, and common areas',
    bidDueDate: daysFromNow(28),
    status: 'draft',
    progress: 0,
    createdAt: daysFromNow(-60),
    updatedAt: daysFromNow(-3),
  },

  // Add bid packages for remaining projects (simplified for brevity)
  // Project 5: Lakeside Luxury Apartments
  {
    id: generateId(),
    bcBidPackageId: generateBCId(),
    bcProjectId: mockBuildingConnectedProjects[4].bcProjectId,
    name: 'Concrete & Masonry',
    description: 'Cast-in-place concrete and masonry work',
    bidDueDate: daysFromNow(10),
    status: 'bidding',
    progress: 0,
    createdAt: daysFromNow(-25),
    updatedAt: daysFromNow(-1),
  },
  {
    id: generateId(),
    bcBidPackageId: generateBCId(),
    bcProjectId: mockBuildingConnectedProjects[4].bcProjectId,
    name: 'Finishes & Appliances',
    description: 'Unit finishes and appliance packages',
    bidDueDate: daysFromNow(10),
    status: 'bidding',
    progress: 0,
    createdAt: daysFromNow(-25),
    updatedAt: daysFromNow(-1),
  },

  // Project 6: Regional Data Center
  {
    id: generateId(),
    bcBidPackageId: generateBCId(),
    bcProjectId: mockBuildingConnectedProjects[5].bcProjectId,
    name: 'Electrical & Power',
    description: 'Primary electrical service and distribution',
    bidDueDate: daysFromNow(35),
    status: 'active',
    progress: 8,
    createdAt: daysFromNow(-40),
    updatedAt: daysFromNow(-5),
  },
  {
    id: generateId(),
    bcBidPackageId: generateBCId(),
    bcProjectId: mockBuildingConnectedProjects[5].bcProjectId,
    name: 'HVAC & Cooling',
    description: 'Mission-critical cooling systems',
    bidDueDate: daysFromNow(35),
    status: 'active',
    progress: 12,
    createdAt: daysFromNow(-40),
    updatedAt: daysFromNow(-5),
  },

  // Project 7: Historic Theater
  {
    id: generateId(),
    bcBidPackageId: generateBCId(),
    bcProjectId: mockBuildingConnectedProjects[6].bcProjectId,
    name: 'Structural Seismic Upgrade',
    description: 'Seismic retrofitting and structural repairs',
    bidDueDate: daysFromNow(18),
    status: 'bidding',
    progress: 0,
    createdAt: daysFromNow(-35),
    updatedAt: daysFromNow(-2),
  },
  {
    id: generateId(),
    bcBidPackageId: generateBCId(),
    bcProjectId: mockBuildingConnectedProjects[6].bcProjectId,
    name: 'Historic Restoration',
    description: 'Plaster, decorative finishes, and millwork restoration',
    bidDueDate: daysFromNow(18),
    status: 'active',
    progress: 5,
    createdAt: daysFromNow(-35),
    updatedAt: daysFromNow(-2),
  },

  // Project 8: University Science Complex
  {
    id: generateId(),
    bcBidPackageId: generateBCId(),
    bcProjectId: mockBuildingConnectedProjects[7].bcProjectId,
    name: 'Lab Casework & Fume Hoods',
    description: 'Laboratory casework, fume hoods, and equipment',
    bidDueDate: daysFromNow(42),
    status: 'active',
    progress: 0,
    createdAt: daysFromNow(-50),
    updatedAt: daysFromNow(-4),
  },
  {
    id: generateId(),
    bcBidPackageId: generateBCId(),
    bcProjectId: mockBuildingConnectedProjects[7].bcProjectId,
    name: 'Process Piping & Lab Gases',
    description: 'Laboratory process piping and gas systems',
    bidDueDate: daysFromNow(42),
    status: 'active',
    progress: 0,
    createdAt: daysFromNow(-50),
    updatedAt: daysFromNow(-4),
  },

  // Project 9: Airport Terminal (awarded)
  {
    id: generateId(),
    bcBidPackageId: generateBCId(),
    bcProjectId: mockBuildingConnectedProjects[8].bcProjectId,
    name: 'Structural Steel & Glazing',
    description: 'Long-span steel and curtain wall systems',
    bidDueDate: daysFromNow(-15),
    status: 'awarded',
    progress: 25,
    createdAt: daysFromNow(-90),
    updatedAt: daysFromNow(-10),
  },
  {
    id: generateId(),
    bcBidPackageId: generateBCId(),
    bcProjectId: mockBuildingConnectedProjects[8].bcProjectId,
    name: 'Baggage Handling Systems',
    description: 'Automated baggage handling and screening',
    bidDueDate: daysFromNow(-15),
    status: 'awarded',
    progress: 20,
    createdAt: daysFromNow(-90),
    updatedAt: daysFromNow(-10),
  },

  // Project 10: Waterfront Hotel
  {
    id: generateId(),
    bcBidPackageId: generateBCId(),
    bcProjectId: mockBuildingConnectedProjects[9].bcProjectId,
    name: 'Marine Construction',
    description: 'Dock repairs and marina improvements',
    bidDueDate: daysFromNow(25),
    status: 'bidding',
    progress: 0,
    createdAt: daysFromNow(-28),
    updatedAt: daysFromNow(-1),
  },
  {
    id: generateId(),
    bcBidPackageId: generateBCId(),
    bcProjectId: mockBuildingConnectedProjects[9].bcProjectId,
    name: 'Hotel FF&E',
    description: 'Furniture, fixtures, and equipment',
    bidDueDate: daysFromNow(25),
    status: 'draft',
    progress: 0,
    createdAt: daysFromNow(-28),
    updatedAt: daysFromNow(-1),
  },
];

// Helper function to get bid packages for a specific project
export const getBidPackagesByProject = (bcProjectId: string): BidPackage[] => {
  return mockBidPackages.filter((pkg) => pkg.bcProjectId === bcProjectId);
};

// Helper function to get project by ID
export const getProjectById = (
  bcProjectId: string
): BuildingConnectedProject | undefined => {
  return mockBuildingConnectedProjects.find((p) => p.bcProjectId === bcProjectId);
};
